/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as ApiRealtimeRouteImport } from './routes/api/realtime'
import { Route as ApiAgentStatusRouteImport } from './routes/api/agent/status'
import { Route as ApiAgentTurnRouteImport } from './routes/api/agent/turn'
import { Route as ApiSandboxRunRouteImport } from './routes/api/sandbox/run'
import { Route as ApiSandboxStatusRouteImport } from './routes/api/sandbox/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeRoute = ApiRealtimeRouteImport.update({
  id: '/api/realtime',
  path: '/api/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentStatusRoute = ApiAgentStatusRouteImport.update({
  id: '/api/agent/status',
  path: '/api/agent/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentTurnRoute = ApiAgentTurnRouteImport.update({
  id: '/api/agent/turn',
  path: '/api/agent/turn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSandboxRunRoute = ApiSandboxRunRouteImport.update({
  id: '/api/sandbox/run',
  path: '/api/sandbox/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSandboxStatusRoute = ApiSandboxStatusRouteImport.update({
  id: '/api/sandbox/status',
  path: '/api/sandbox/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/agent/status': typeof ApiAgentStatusRoute
  '/api/agent/turn': typeof ApiAgentTurnRoute
  '/api/sandbox/run': typeof ApiSandboxRunRoute
  '/api/sandbox/status': typeof ApiSandboxStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/agent/status': typeof ApiAgentStatusRoute
  '/api/agent/turn': typeof ApiAgentTurnRoute
  '/api/sandbox/run': typeof ApiSandboxRunRoute
  '/api/sandbox/status': typeof ApiSandboxStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/agent/status': typeof ApiAgentStatusRoute
  '/api/agent/turn': typeof ApiAgentTurnRoute
  '/api/sandbox/run': typeof ApiSandboxRunRoute
  '/api/sandbox/status': typeof ApiSandboxStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspace'
    | '/api/realtime'
    | '/api/agent/status'
    | '/api/agent/turn'
    | '/api/sandbox/run'
    | '/api/sandbox/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workspace'
    | '/api/realtime'
    | '/api/agent/status'
    | '/api/agent/turn'
    | '/api/sandbox/run'
    | '/api/sandbox/status'
  id:
    | '__root__'
    | '/'
    | '/workspace'
    | '/api/realtime'
    | '/api/agent/status'
    | '/api/agent/turn'
    | '/api/sandbox/run'
    | '/api/sandbox/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ApiRealtimeRoute: typeof ApiRealtimeRoute
  ApiAgentStatusRoute: typeof ApiAgentStatusRoute
  ApiAgentTurnRoute: typeof ApiAgentTurnRoute
  ApiSandboxRunRoute: typeof ApiSandboxRunRoute
  ApiSandboxStatusRoute: typeof ApiSandboxStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime': {
      id: '/api/realtime'
      path: '/api/realtime'
      fullPath: '/api/realtime'
      preLoaderRoute: typeof ApiRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/status': {
      id: '/api/agent/status'
      path: '/api/agent/status'
      fullPath: '/api/agent/status'
      preLoaderRoute: typeof ApiAgentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/turn': {
      id: '/api/agent/turn'
      path: '/api/agent/turn'
      fullPath: '/api/agent/turn'
      preLoaderRoute: typeof ApiAgentTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sandbox/run': {
      id: '/api/sandbox/run'
      path: '/api/sandbox/run'
      fullPath: '/api/sandbox/run'
      preLoaderRoute: typeof ApiSandboxRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sandbox/status': {
      id: '/api/sandbox/status'
      path: '/api/sandbox/status'
      fullPath: '/api/sandbox/status'
      preLoaderRoute: typeof ApiSandboxStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRoute,
  ApiRealtimeRoute: ApiRealtimeRoute,
  ApiAgentStatusRoute: ApiAgentStatusRoute,
  ApiAgentTurnRoute: ApiAgentTurnRoute,
  ApiSandboxRunRoute: ApiSandboxRunRoute,
  ApiSandboxStatusRoute: ApiSandboxStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
